export const labels = {
  en: {
    title: "Route map",
    route: "Route",
    expand: "Expand map",
    collapse: "Close expanded map",
    close_segment: "Close segment details",
    close_layers: "Close map layers",
    forecast_layer: "Forecast layer",
    data_gaps: "Incomplete data",
    appearance: "Appearance",
    road_cameras: "Road cameras",
    weather_stations: "Weather stations",
    air_temperature: "Air temperature",
    observation_time: "Observation time",
    close_source: "Close source details",
    sources_loading: "Loading nearby sources…",
    cameras_unavailable: "Camera discovery unavailable",
    weather_unavailable: "Weather stations unavailable",
    close_camera: "Close camera",
    camera_loading: "Loading image…",
    camera_unavailable: "Image unavailable",
    camera_status: "Source status",
    camera_available: "Images available",
    source_group: "{count} sources",
    collapse_sources: "Collapse group",
    layers: "Map layers and legend",
    attribution: "Map attribution",
    theme_modes: { auto: "Auto", light: "Light", dark: "Dark" },
    map_styles: {
      default: "Default",
      colorful: "Colorful",
      natural: "Natural",
      muted: "Muted",
      gray: "Gray",
      toner: "Toner",
    },
    editor: {
      device_id: "Route",
      title: "Title",
      height: "Map height",
      default_mode: "Initial layer",
      legend_expanded: "Expand legend",
      theme_mode: "Theme mode",
      map_style: "Map style",
      show_cameras: "Show road cameras",
      show_weather: "Show weather stations",
      weather_distance_m: "Maximum station distance from route",
      camera_distance_m: "Maximum camera distance from route",
    },
    unrecognized: "Unrecognized values",
    unauthorized: "Access denied",
    invalid_route: "Select a Statens vegvesen route",
    fit: "Fit route",
    legend: "Segments in route corridor",
    loading: "Loading route…",
    unavailable: "Route unavailable",
    disconnected: "Home Assistant disconnected",
    upgrade: "Update the Statens vegvesen integration to use this card",
    webgl: "Interactive maps need WebGL 2",
    basemap: "Some background map data could not be loaded",
    retry: "Retry",
    forecast: "Forecast valid time",
    empty: "No forecast segments",
    condition: "Road condition",
    temperature: "Road temperature",
    slip: "Slipperiness",
    missing: "Missing data",
    segment: "Segment",
    start: "Start",
    end: "Destination",
    no_geometry: "Segments without geometry",
    NoNewPrecipitation: "No new precipitation",
    WetRoadSurface: "Wet road surface",
    IceOrFrost: "Ice or frost",
    SnowCover: "Snow cover",
    DriftingSnow: "Drifting snow",
    ErrorOrNoData: "Error or no data",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  nb: {
    title: "Rutekart",
    route: "Rute",
    expand: "Utvid kartet",
    collapse: "Lukk utvidet kart",
    close_segment: "Lukk strekningsdetaljer",
    close_layers: "Lukk kartlag",
    forecast_layer: "Prognoselag",
    data_gaps: "Ufullstendige data",
    appearance: "Utseende",
    road_cameras: "Veikameraer",
    weather_stations: "Værstasjoner",
    air_temperature: "Lufttemperatur",
    observation_time: "Observasjonstidspunkt",
    close_source: "Lukk kildedetaljer",
    sources_loading: "Laster kilder langs ruten…",
    cameras_unavailable: "Kamerasøket er utilgjengelig",
    weather_unavailable: "Værstasjonene er utilgjengelige",
    close_camera: "Lukk kamera",
    camera_loading: "Laster bilde…",
    camera_unavailable: "Bildet er utilgjengelig",
    camera_status: "Kildestatus",
    camera_available: "Bilder tilgjengelig",
    source_group: "{count} kilder",
    collapse_sources: "Lukk gruppen",
    layers: "Kartlag og tegnforklaring",
    attribution: "Kartkilder",
    theme_modes: { auto: "Automatisk", light: "Lys", dark: "Mørk" },
    map_styles: {
      default: "Standard",
      colorful: "Fargerikt",
      natural: "Naturlig",
      muted: "Dempet",
      gray: "Grå",
      toner: "Toner",
    },
    editor: {
      device_id: "Rute",
      title: "Tittel",
      height: "Karthøyde",
      default_mode: "Kartlag ved åpning",
      legend_expanded: "Utvid tegnforklaringen",
      theme_mode: "Temamodus",
      map_style: "Kartstil",
      show_cameras: "Vis veikameraer",
      show_weather: "Vis værstasjoner",
      weather_distance_m: "Maksimal stasjonsavstand fra ruten",
      camera_distance_m: "Maksimal kameraavstand fra ruten",
    },
    unrecognized: "Ukjente kildeverdier",
    unauthorized: "Ingen tilgang",
    invalid_route: "Velg en rute fra Statens vegvesen",
    fit: "Vis hele ruten",
    legend: "Strekninger i rutekorridoren",
    loading: "Laster ruten…",
    unavailable: "Ruten er utilgjengelig",
    disconnected: "Ingen tilkobling til Home Assistant",
    upgrade: "Oppdater Statens vegvesen-integrasjonen for å bruke dette kortet",
    webgl: "Interaktive kart krever WebGL 2",
    basemap: "Deler av bakgrunnskartet kunne ikke lastes",
    retry: "Prøv igjen",
    forecast: "Prognosen gjelder for",
    empty: "Ingen prognosestrekninger",
    condition: "Føreforhold",
    temperature: "Veibanetemperatur",
    slip: "Glatthet",
    missing: "Mangler data",
    segment: "Strekning",
    start: "Start",
    end: "Mål",
    no_geometry: "Strekninger uten geometri",
    NoNewPrecipitation: "Ingen ny nedbør",
    WetRoadSurface: "Våt veibane",
    IceOrFrost: "Is eller rim",
    SnowCover: "Snødekke",
    DriftingSnow: "Snøfokk",
    ErrorOrNoData: "Feil eller ingen data",
    low: "Lav",
    medium: "Middels",
    high: "Høy",
  },
};
export const language = (hass) =>
  hass?.locale?.language?.startsWith("nb") ||
  hass?.locale?.language === "no" ||
  hass?.language?.startsWith("nb")
    ? "nb"
    : "en";
