export const labels = {
  en: {
    title: "Route map",
    highest: "Highest forecast slipperiness",
    unrecognized: "Unrecognized values",
    unauthorized: "Access denied",
    invalid_route: "Select a Statens vegvesen route forecast sensor",
    fit: "Fit route",
    legend: "Segments in route corridor",
    loading: "Loading route…",
    unavailable: "Route unavailable",
    disconnected: "Home Assistant disconnected",
    upgrade: "Update the Statens vegvesen integration to use this card",
    webgl: "Interactive maps need WebGL 2. Forecast summaries are shown below.",
    basemap: "Some background map data could not be loaded",
    retry: "Retry",
    forecast: "Forecast valid time",
    empty: "No forecast segments",
    condition: "Road condition",
    temperature: "Road temperature",
    slip: "Slipperiness",
    missing: "Missing data",
    segment: "Segment",
    start: "Start",
    end: "Destination",
    no_geometry: "Segments without geometry",
    NoNewPrecipitation: "No new precipitation",
    WetRoadSurface: "Wet road surface",
    IceOrFrost: "Ice or frost",
    SnowCover: "Snow cover",
    DriftingSnow: "Drifting snow",
    ErrorOrNoData: "Error or no data",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  nb: {
    title: "Rutekart",
    highest: "Høyeste varslede glatthet",
    unrecognized: "Ukjente kildeverdier",
    unauthorized: "Ingen tilgang",
    invalid_route: "Velg en ruteprognosesensor fra Statens vegvesen",
    fit: "Vis hele ruten",
    legend: "Strekninger i rutekorridoren",
    loading: "Laster ruten…",
    unavailable: "Ruten er utilgjengelig",
    disconnected: "Ingen tilkobling til Home Assistant",
    upgrade: "Oppdater Statens vegvesen-integrasjonen for å bruke dette kortet",
    webgl:
      "Interaktive kart krever WebGL 2. Prognosesammendrag vises nedenfor.",
    basemap: "Deler av bakgrunnskartet kunne ikke lastes",
    retry: "Prøv igjen",
    forecast: "Prognosen gjelder for",
    empty: "Ingen prognosestrekninger",
    condition: "Føreforhold",
    temperature: "Veibanetemperatur",
    slip: "Glatthet",
    missing: "Mangler data",
    segment: "Strekning",
    start: "Start",
    end: "Mål",
    no_geometry: "Strekninger uten geometri",
    NoNewPrecipitation: "Ingen ny nedbør",
    WetRoadSurface: "Våt veibane",
    IceOrFrost: "Is eller rim",
    SnowCover: "Snødekke",
    DriftingSnow: "Snøfokk",
    ErrorOrNoData: "Feil eller ingen data",
    low: "Lav",
    medium: "Middels",
    high: "Høy",
  },
};
export const language = (hass) =>
  hass?.locale?.language?.startsWith("nb") ||
  hass?.locale?.language === "no" ||
  hass?.language?.startsWith("nb")
    ? "nb"
    : "en";
