[project]
name = "ha-vegvesen-minimum-tests"
version = "0.12.3"
requires-python = ">=3.13.11,<3.14"
dependencies = [
    "pyproj==3.8.0",
    "shapely==2.1.2",
    "pycares==4.11.0", # aiodns 3.5.0 is incompatible with pycares 5
    "aioresponses==0.7.9",
    "homeassistant==2025.12.0",
    "pytest-homeassistant-custom-component==0.13.298",
    "PyTurboJPEG==1.8.0",
]

[dependency-groups]
smoke = [
    "ha-ffmpeg==3.2.2",
    "hassil==3.5.0",
    "home-assistant-frontend==20251203.0", # HA 2025.12.0 frontend requirement
    "home-assistant-intents==2025.12.2",
    "mutagen==1.47.0",
    "pymicro-vad==1.0.1",
    "pyspeex-noise==1.0.2",
]

[tool.uv]
package = false
build-constraint-dependencies = ["pybind11==3.1.0", "setuptools==84.0.0", "wheel==0.48.0"]

[tool.uv.extra-build-dependencies]
lru-dict = ["ziglang==0.15.2"]
pymicro-vad = ["ziglang==0.15.2"]
pyspeex-noise = ["ziglang==0.15.2"]
