[project]
name = "ha-vegvesen-minimum-tests"
version = "0.6.2"
requires-python = ">=3.13.11,<3.14"
dependencies = [
    "pyproj==3.8.0",
    "shapely==2.1.2",
    "pycares==4.11.0", # aiodns 3.5.0 is incompatible with pycares 5
    "aioresponses==0.7.9",
    "homeassistant==2025.12.0",
    "pytest-homeassistant-custom-component==0.13.298",
    "PyTurboJPEG==1.8.0",
]

[tool.uv]
package = false
build-constraint-dependencies = ["setuptools==84.0.0", "wheel==0.48.0"]

[tool.uv.extra-build-dependencies]
lru-dict = ["ziglang==0.15.2"]
