get_route_forecasts:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vegvesen
    forecast_time:
      selector:
        datetime:
    include_segments:
      default: true
      selector:
        boolean:
